import fs from "fs";
import { Page } from "puppeteer";

const OUTPUT_DIR = "./src/data/scraper/output";

/**
 * Parse and save all the rowIds
 */
export async function parseRowIds(page: Page): Promise<void> {
  // Generate links to retrieve
  const anchors = await page.$$("a[href='#HistoryModal']");
  const rowIdPromises = anchors.map((anchor) =>
    anchor.evaluate((e) => e.getAttribute("data-id"))
  );
  const rowIds = await Promise.all(rowIdPromises);

  fs.writeFileSync(
    `${OUTPUT_DIR}/rowIds.json`,
    JSON.stringify(rowIds, null, 2)
  );
}

/**
 * Load row IDs from a saved file generated by parseRowIds
 */
export function loadRowIds(): string[] {
  const data = fs.readFileSync(`${OUTPUT_DIR}/rowIds.json`, "utf-8");
  const rowIds = JSON.parse(data);

  return rowIds;
}
