import { Bill } from ".prisma/client";
import axios from "axios";
import FormData from "form-data";
import fs from "fs";
import { ElementHandle, Page } from "puppeteer";
import getBrowser from "../util/getBrowser";
import parseBillHistoryRows from "./billHistoryParser";

const BASE_URL = "https://www.congress.gov.ph/legisdocs/?v=bills";
const MODAL_URL = "https://www.congress.gov.ph/legisdocs/fetch_history.php";
const OUTPUT_DIR = "./src/data/scraper/output";

type TableRow = ElementHandle<HTMLTableRowElement>;

/**
 * Request for the modal content for a specific row ID
 */
async function requestModal(page: Page, rowId: string): Promise<TableRow[]> {
  const formData = new FormData();
  formData.append("rowid", rowId);
  const { data } = await axios({
    method: "post",
    url: MODAL_URL,
    data: formData,
  });

  page.setContent(data);
  const rows = await page?.$$("tr");

  if (rows == undefined) {
    throw new Error("Could not parse history modal rows");
  }

  return rows as any;
}

/**
 * Parse and save all the rowIds
 */
async function parseRowIds(page: Page): Promise<void> {
  // Generate links to retrieve
  const anchors = await page.$$("a[href='#HistoryModal']");
  const rowIdPromises = anchors.map((anchor) =>
    anchor.evaluate((e) => e.getAttribute("data-id"))
  );
  const rowIds = await Promise.all(rowIdPromises);

  fs.writeFileSync(
    `${OUTPUT_DIR}/rowIds.json`,
    JSON.stringify(rowIds, null, 2)
  );
}

/**
 * Load row IDs from a saved file generated by parseRowIds
 */
function loadRowIds(): string[] {
  const data = fs.readFileSync(`${OUTPUT_DIR}/rowIds.json`, "utf-8");
  const rowIds = JSON.parse(data);

  return rowIds;
}

async function main() {
  // Visit page
  const browser = await getBrowser();
  const modalPage = await browser.newPage();

  // Parse each page
  const bills = [];
  const errors = [];
  let counter = 0;

  // const rowIds = loadRowIds();
  const rowIds = ["#HB00018-19"];
  for (const rowId of rowIds) {
    console.log("Loading", rowId);
    counter++;

    try {
      const modalRows = await requestModal(modalPage, rowId);
      const billHistory = await parseBillHistoryRows(modalRows);
      console.log("Loaded", rowId, billHistory.billNum);

      bills.push(billHistory);

      if (counter % 5 == 0) {
        // Periodically save to disk
        fs.writeFileSync(
          `${OUTPUT_DIR}/bills.json`,
          JSON.stringify(bills, null, 2)
        );
      }
    } catch (err) {
      errors.push(rowId);
      console.error("Error", err);
    }
  }
  console.log(counter, "bills processed");

  fs.writeFileSync(`${OUTPUT_DIR}/bills.json`, JSON.stringify(bills, null, 2));
  console.log("Errors", errors);

  await modalPage.close();
  console.log("Done");
}

main();
